# Enhanced Client Settings

# How many times to iterate
runs: 24
# Time interval between the start of two different runs (in minutes)
runs_interval: 60
# How much time each client execution should last (in seconds)
runs_step_duration: 30
# Iperf Destinations
iperf_destinations:
- name: "Deployed-Iperf3-Server"
  ip: "34.56.78.90"
  port: "80"
# Ping Destinations
ping_destinations:
- name: "Pingable-Host"
  ip: "23.45.67.89"
# Interval between ping executions (in seconds)
ping_interval: 30
# List of endpoints to test E2E latency, defined by its name/description and its address
endpoints:
- description: "1_Example-Address"
  destination: "12.34.56.67:8080"
- description: "2_Example-Hostname"
  destination: "latency-tester.example.com"
# List of intervals between the send of two messages to test E2E latency
intervals:
- 10
- 25
- 50
- 100
- 250
- 500
# List of request message sizes to test E2E latency
msg_sizes:
- 1024
- 10240
- 102400
- 1024000
# Response message size
response_size: 1024
# True if TLS enabled
tls_enabled: "true"
# Execution directory (if in Docker, this must coincide with the mapped directory)
exec_dir: "/execdir/"

# Plotting Settings

# How many percentiles to remove from the extremities of the plots (default 0 if omitted)
percentiles_to_remove: 1
# The minimum value in the plot for the RTT (automatically obtained if omitted)
#rtt_min: 10
# The maximum value in the plot for the RTT (automatically obtained if omitted)
# rtt_max: 20
# The runs we selectively want to plot (default all runs if omitted)
#runs_to_plot:
#- 1
#- 3
