---
apiVersion: v1
data:
  mosquitto.conf:
    allow_anonymous true

    listener 8080
    set_tcp_nodelay true

    log_type all
    log_dest stdout
    log_timestamp true
    log_timestamp_format %Y-%m-%dT%H:%M:%S
kind: ConfigMap
metadata:
  name: mosquitto

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  selector:
    app.kubernetes.io/name: mosquitto
  ports:
  - port: 8080
    name: broker
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0
        volumeMounts:
        - mountPath: /mosquitto/config
          name: mosquitto-config
      volumes:
      - name: mosquitto-config
        configMap:
          name: mosquitto
