---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-tester-mqtt
  labels:
    app.kubernetes.io/name: latency-tester-mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: latency-tester-mqtt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: latency-tester-mqtt
    spec:
      containers:
      - name: latency-tester-mqtt
        image: giorio94/latency-tester-mqtt-server:v0.1
        args:
        - --broker=tcp://mosquitto:8080
