---
- name: Deploy latency-tester Clients
  hosts: clients
  vars:
    workdir: "test"
    settings_file: "settings-example.yaml"
    tool_version: "1.0.0"

  tasks:

  - name: Print the gateway for each host when defined
    ansible.builtin.debug:
      msg: "{{ ansible_user_dir }}"

  - name: Create workdir
    file:
      path: "{{ ansible_user_dir }}/{{ workdir }}"
      state: directory

  - name: Move settings file to workdir
    ansible.builtin.copy:
      src: "{{ settings_file }}"
      dest: "{{ ansible_user_dir }}/{{ workdir }}"

  - name: Run docker
    command: "docker run -v {{ ansible_user_dir }}/{{ workdir }}:/execdir --rm -d richimarchi/latency-tester_enhanced:{{ tool_version }} /execdir/{{ settings_file }}"
